services:

  backend:
    image: ghcr.io/navreetsingh13/rbac-backend:latest
    container_name: rbac-backend
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "5000:5000"

    networks:
      - rbac-network

    volumes:
      - /share/DataVol1/Docker/rbac/uploads:/app/uploads
      - /share/DataVol1/Docker/rbac/logs:/app/logs

  frontend:
    image: ghcr.io/navreetsingh13/rbac-frontend:latest
    container_name: rbac-frontend
    restart: unless-stopped

    ports:
      - "3000:80"

    networks:
      - rbac-network

networks:
  rbac-network:
    driver: bridge
